### ISSUE TITLE
Focus on content

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#11]
In edit and view, it would be nice if the map is focused on the objects chosen by the filter.

**Comment by stumpdk** [comment]
Closed, as this feature is now implemented in the show section (but not edit).

**Comment by jacobandresen** [comment]
Looks like this is not on the master branch currently. I'll just put it in.

**Comment by jacobandresen** [comment]
i added support for polygons also (see fitTagGroupInBounds in TagMap.js)

**Comment by jacobandresen** [comment]
Polygon zoom does not work

**Comment by stumpdk** [comment]
It works on selection when zooming out, but it doesn't zoom in.

**Comment by stumpdk** [comment]
Maybe <a href="https://github.com/jacobandresen/TagMap/commit/bee4b3ac92db0f4af45e83468e07a7ea1fcf81e1">this</a> solution can be used.

**Comment by jacobandresen** [comment]
I fixed an error that wrecked the geometries in updateInfo. This error caused the errors in fitTagGroupInBounds

**Comment by jacobandresen** [comment]
we can now focus on content in selected markers.

**Comment by stumpdk** [comment]
The feature still doesn't fully work.
It doesn't zoom in when selection markers in a smaller area.

**Comment by stumpdk** [comment]
I'm not certain if this is caused by some messy geo references in some of the tags, but zooming in isn't working.
This <a href="https://github.com/jacobandresen/TagMap/commit/bee4b3ac92db0f4af45e83468e07a7ea1fcf81e1">solution</a> gives the same result.

**Comment by jacobandresen** [comment]
this commit https://github.com/jacobandresen/TagMap/commit/92e998036371a699d77fc099f8da8953e7d720c4 fixes the zoom problem. The main issue was that we forgot to clear the tagGroup when navigating
