### ISSUE TITLE
Map mocing when clicking marker link

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#32]
If the map is at the bottom of a page, and the marker is clicked, the screen jumps to the top. This is not user friendly behavior.
Perhaps another href than the "#" should be used?

**Comment by jacobandresen** [comment]
we'll just stop the link event for now. That should solve the problem.

**Comment by stumpdk** [comment]
Nice! :)

**Comment by stumpdk** [comment]
There is still a problem here. It works with the first click, but after reaching the new marker, a new click doesn't select a new marker.
Maybe it is because the enableTagLinks-function isn't run for a new marker?

**Comment by jacobandresen** [comment]
nice catch. fixed

**Comment by stumpdk** [comment]
Nice! :)
